### ISSUE TITLE
Unclear Instructions from StackOverflowNER

### ISSUE THREAD

**Issue by KareemAlaa2001** [lanwuwei/BERTOverflow#1]
Hi, I was linked to this repo from the StackOverflowNER repo where the readme stated that I should install the pre-trained model from here. However, the only files in the repo are a readme and a PNG, and the readme just contains code on training the BERTOverflow model. I've checked the google drive folder, but I am unsrue which of those files I should install and where in order to get the entire StackOverflowNER library working on a file of my own.

Fantastic work on the paper by the way; I hope you can respond soon though since this could potentially make for a fantastic addition to my final year project at university!

Thanks!

**Comment by lanwuwei** [comment]
Hi, this is just a reference for BERT pre-training with your own data. First, you need to download the original BERT [codebase](https://github.com/google-research/bert), then apply for TPU usage through [TFRC](https://www.tensorflow.org/tfrc), finally follow this readme for BERT pre-training.

**Comment by KareemAlaa2001** [comment]
> Hi, this is just a reference for BERT pre-training with your own data. First, you need to download the original BERT [codebase](https://github.com/google-research/bert), then apply for TPU usage through [TFRC](https://www.tensorflow.org/tfrc), finally follow this readme for BERT pre-training.

Will it be necessary for me to pre-train BERT in order to use the wider StackOverflowNER library on my data? For reference, my dataset is taken from the stack exchange dump. 

If not, is a trained version of this model already pre-packaged with the library (in case I missed it in there)

I know these questions are probably a bit basic, but I am genuinely not sure if there was something I missed while going through the readmes. 

Thanks!

**Comment by lanwuwei** [comment]
Please check this [link](https://huggingface.co/lanwuwei/BERTOverflow_stackoverflow_github) for our pre-trained model, if you have your own data, you can continue pre-training it based on our checkpoint.
